#@TYPE: Machine
#@NAME: DH STM32MP25 DHCOS SoM on DHSBC carrier board
#@SOC:  ST STM32MP25
#@DESCRIPTION: Machine configuration for DH STM32MP25 DHCOS SoM on DHSBC carrier board

require conf/machine/include/dh-stm32mp2-common.inc

UBOOT_MAKE_TARGET := "u-boot-nodtb.bin u-boot.dtb all"
UBOOT_BINARY := "u-boot-nodtb.bin"
UBOOT_SUFFIX ?= "bin"
SPL_BINARY := ""
do_image_wic[depends] += "trusted-firmware-a:do_deploy"

# U-Boot bootloader
UBOOT_MACHINE = "stm32mp25_dhcos_dhsbc_defconfig"

# Linux kernel
KERNEL_DEVICETREE = " \
	st/stm32mp255c-dhcos-dhsbc.dtb \
	st/stm32mp255c-dhcos-dhsbc-overlay-imx219-x10.dtbo \
	"

# Ship kernel modules
MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " \
	cypress-firmware-bcm43xx-bt-patch-cyw55500a1-2fy \
	cypress-firmware-bcm43xx-fmac-nvram-bcm55500-2fy-sdio \
	ifx-firmware-bcm43xx-fmac-fw-bcm55500-sdio \
	"
