FILESEXTRAPATHS:prepend := "${THISDIR}/upports:"
COMPATIBLE_MACHINE:dh-stm32mp25-dhsom = "dh-stm32mp25-dhsom"
TFA_PLATFORM:dh-stm32mp25-dhsom = "stm32mp2"
TFA_BUILD_TARGET:dh-stm32mp25-dhsom = "all fip"
TFA_INSTALL_TARGET:dh-stm32mp25-dhsom = "tf-a-stm32mp25xx-dhcos-som.stm32 fip.bin"
TFA_BUILD_TARGET:append:dh-stm32mp25-dhcos-bb = " fip-ddr"
TFA_INSTALL_TARGET:append:dh-stm32mp25-dhcos-bb = " fip-ddr.bin"

do_compile[depends] += "${@'optee-os:do_deploy u-boot-mainline:do_deploy' if 'dh-stm32mp25-dhsom' in d.getVar('MACHINEOVERRIDES', True).split(':') else ' '}"

# Workaround for ST downstream 0145-feat-st-ddr-add-STM32MP2-PHY-driver.patch
# which includes binary blobs in the patch file. OE default patchtool, quilt,
# rejects such bad patches. Work around this by using git to apply the patches.
PATCHTOOL:dh-stm32mp25-dhsom = "git"

EXTRA_OEMAKE:append:dh-stm32mp25-dhsom = " \
	BL32=${DEPLOY_DIR_IMAGE}/optee/tee-header_v2.bin \
	BL32_EXTRA1=${DEPLOY_DIR_IMAGE}/optee/tee-pager_v2.bin \
	BL33=${DEPLOY_DIR_IMAGE}/u-boot-nodtb.bin \
	BL33_CFG=${DEPLOY_DIR_IMAGE}/u-boot.dtb \
	DTB_FILE_NAME=stm32mp25xx-dhcos-som.dtb \
	SPD=opteed \
	STM32MP_DDR_FW=drivers/st/ddr/phy/firmware/bin/stm32mp2/lpddr4_pmu_train.bin \
	STM32MP_LPDDR4_TYPE=1 \
	STM32MP_EMMC=1 \
	STM32MP_SDMMC=1 \
	STM32MP_SPI_NOR=1 \
	VERSION=${PV} \
	"

EXTRA_OEMAKE:append:dh-stm32mp25-dhcos-bb = " STM32MP_USB_PROGRAMMER=1"

SRC_URI:append:dh-stm32mp25-dhsom = " \
	file://0001-feat-st-add-ST-specific-version.patch \
	file://0002-feat-memmap-add-RELA-section-display.patch \
	file://0003-feat-bl-allow-platform-to-define-backup-partitions.patch \
	file://0004-feat-stm32mp1-add-FWU-with-boot-from-NAND.patch \
	file://0005-feat-fwu-add-metadata-generator-tools.patch \
	file://0006-feat-stm32mp1-default-first-metadata-for-FWU.patch \
	file://0007-feat-makefile-add-macro-and-variable-to-generate-met.patch \
	file://0008-feat-stm32mp1-generate-default-metadata-with-bl2-ima.patch \
	file://0009-feat-st-clock-add-function-to-control-MCU-subsystem.patch \
	file://0010-refactor-stm32mp1-move-the-MCU-security-to-BL32.patch \
	file://0011-feat-dt-bindings-add-MCE-DT-bindings-for-STM32MP13.patch \
	file://0012-feat-st-drivers-add-Memory-Cipher-Engine-driver.patch \
	file://0013-feat-stm32mp1-enable-MCE-driver-for-STM32MP13.patch \
	file://0014-feat-stm32mp1-prepare-DDR-secure-area-encryption-for.patch \
	file://0015-refactor-st-i2c-use-fdt_read_uint32_default.patch \
	file://0016-feat-st-i2c-compute-dynamically-I2C-timings.patch \
	file://0017-feat-debug-add-one-register-in-asm-print-functions.patch \
	file://0018-feat-st-uart-add-timeout-management.patch \
	file://0019-feat-stm32mp1-fdts-add-MCE-support-for-STM32MP13-DK-.patch \
	file://0020-feat-stm32mp1-manage-potential-tamper-while-boot.patch \
	file://0021-feat-st-reset-add-system-reset-management.patch \
	file://0022-feat-stm32mp1-add-Backup-SRAM-definitions.patch \
	file://0023-feat-st-protect-access-on-PWR-registers.patch \
	file://0024-feat-stm32mp1-add-low-power-context-management.patch \
	file://0025-feat-stm32mp1-update-boot_api.h-for-low-power.patch \
	file://0026-feat-st-manage-ROM-code-boot_action-field.patch \
	file://0027-feat-stm32mp1-add-stm32mp1_is_wakeup_from_standby.patch \
	file://0028-feat-st-ddr-add-DDR-self-refresh-management.patch \
	file://0029-refactor-st-ddr-gather-redundant-procedures-as-gener.patch \
	file://0030-feat-st-ddr-add-generic-services-to-manage-quasi-dyn.patch \
	file://0031-fix-st-ddr-manage-quasi-dynamic-register-modificatio.patch \
	file://0032-fix-st-ddr-manage-refresh-related-register-modificat.patch \
	file://0033-refactor-st-ddr-rename-timeout-definitions.patch \
	file://0034-refactor-st-ddr-create-definitions-for-delays.patch \
	file://0035-fix-st-ddr-manage-AXI-ports-and-HIF-when-updating-QD.patch \
	file://0036-feat-st-pmic-add-a-switch-off-function.patch \
	file://0037-feat-stm32mp1-check-an-address-is-inside-backup-SRAM.patch \
	file://0038-feat-dt-bindings-add-low-power-defines-for-STM32MP1.patch \
	file://0039-feat-stm32mp1-manage-low-power.patch \
	file://0040-feat-stm32mp1-save-zq0cr0-in-backup-context-at-boot-.patch \
	file://0041-feat-stm32mp1-check-the-context-is-saved.patch \
	file://0042-feat-stm32mp1-add-MCE-master-key-services-for-STM32M.patch \
	file://0043-feat-stm32mp1-save-restore-MCE-key.patch \
	file://0044-feat-st-clock-add-function-to-restore-generic-timer-.patch \
	file://0045-feat-stm32mp1-add-LPLV-Stop2-mode.patch \
	file://0046-feat-stm32mp15-fdts-fulfill-diversity-for-STM32M15x-.patch \
	file://0047-feat-stm32mp15-fdts-add-stm32mp157d-dk1-board.patch \
	file://0048-feat-stm32mp15-fdts-add-stm32mp157f-dk2-board.patch \
	file://0049-feat-stm32mp15-fdts-adapt-stm32mp157a-dk1-board-to-s.patch \
	file://0050-feat-stm32mp15-fdts-add-stm32mp157x-ed1-boards.patch \
	file://0051-feat-stm32mp15-fdts-add-stm32mp157x-ev1-boards.patch \
	file://0052-feat-stm32mp15-fdts-align-SoC-DT-with-Linux.patch \
	file://0053-feat-stm32mp15-fdts-apply-RCC-security.patch \
	file://0054-fix-stm32mp1-do-not-modify-CPU-voltage-after-standby.patch \
	file://0055-feat-stm32mp1-fdts-move-RNG1-to-CSI-to-improve-rando.patch \
	file://0056-fix-st-clock-do-not-reconfigure-LSE.patch \
	file://0057-feat-st-pmic-force-PMIC-and-its-I2C-secure-in-BL2.patch \
	file://0058-refactor-stm32mp13-fdts-remove-secure-status-for-PMI.patch \
	file://0059-docs-dt-bindings-add-device-tree-bindings-used-on-ST.patch \
	file://0060-feat-st-regulator-add-enable-ramp-delay-in-BL2.patch \
	file://0061-feat-dt-bindings-describe-GPIO-banks-and-config.patch \
	file://0062-refactor-st-use-GPIO-banks-definition-from-bindings.patch \
	file://0063-feat-st-gpio-add-set-GPIO-config-API.patch \
	file://0064-feat-st-regulator-introduce-STM32-GPIO-regulator.patch \
	file://0065-feat-stm32mp1-enable-GPIO-regulator-on-STM32MP1.patch \
	file://0066-feat-stm32mp15-remove-OP-TEE-shared-mem.patch \
	file://0067-feat-stm32mp1-always-boot-at-650MHz.patch \
	file://0068-feat-st-clock-don-t-gate-ungate-an-oscillator-if-it-.patch \
	file://0069-feat-stm32mp1-default-load-optee-in-DDR.patch \
	file://0070-fix-stm32mp1-flush-data-cache-at-the-end-of-BL2.patch \
	file://0071-fix-stm32mp1-check-DDR-refresh-to-restore-firewall-c.patch \
	file://0072-refactor-st-drivers-export-struct-stm32_mce_region_s.patch \
	file://0073-feat-stm32mp13-save-restore-DDRMCE-config.patch \
	file://0074-feat-st-drivers-add-stm32_mce_reload_configuration.patch \
	file://0075-feat-fwu-introduce-plat_fwu_is_enabled.patch \
	file://0076-feat-st-add-a-function-to-skip-storage-init-after-st.patch \
	file://0077-feat-st-skip-storage-init-after-standby-if-possible.patch \
	file://0078-feat-stm32mp1-add-hypervisor-mode-for-bl33.patch \
	file://0079-docs-stm32mp15-new-RCC-DT-bindings.patch \
	file://0080-feat-dt-bindings-new-RCC-DT-bindings.patch \
	file://0081-feat-stm32mp1-fdts-new-RCC-DT-bindings-for-STM32MP1.patch \
	file://0082-feat-st-clock-update-with-new-bindings.patch \
	file://0083-refactor-st-bsec-remove-BSEC_DEN_ALL_MSK.patch \
	file://0084-refactor-st-clock-remove-BL32-support-on-STM32MP13.patch \
	file://0085-refactor-stm32mp1-move-is_wakeup_from_standby-in-pla.patch \
	file://0086-feat-stm32mp1-handle-DDR-power-supplies.patch \
	file://0087-feat-dt-bindings-SPIx-bus-clocks-are-missing.patch \
	file://0088-feat-stm32mp13-fdts-remove-pll1-settings.patch \
	file://0089-feat-stm32mp1-manage-STM32MP15-rev.Y.patch \
	file://0090-refactor-st-bsec-remove-bsec_write_debug_conf.patch \
	file://0091-feat-stm32mp1-fdts-use-iwdg1-instead-of-iwdg2.patch \
	file://0092-feat-st-crypto-resolve-MISRA-warning-in-HASH.patch \
	file://0093-feat-stm32mp1-fdts-remove-PLL1-config.patch \
	file://0094-feat-st-lock-the-encryption-key-at-the-end-of-BL2.patch \
	file://0095-feat-stm32mp1-add-a-regulator-supply-function-for-sy.patch \
	file://0096-fix-st-uart-correct-UART-enable-test-in-flush-functi.patch \
	file://0097-fix-dt-bindings-update-STM32MP2-clock-and-reset-bind.patch \
	file://0098-feat-st-clock-add-stm32mp2_clk-driver.patch \
	file://0099-fix-st-clock-force-SRAM1-and-SRAM2-clock-enable.patch \
	file://0100-feat-st-clock-do-not-reconfigure-STGEN-in-BL2.patch \
	file://0101-feat-st-reset-add-stm32mp2_reset-driver.patch \
	file://0102-feat-st-bsec-add-driver-for-the-new-IP-version-BSEC3.patch \
	file://0103-feat-stm32mp2-add-defines-for-the-PWR-peripheral.patch \
	file://0104-feat-stm32mp2-add-RIF-registers-description.patch \
	file://0105-feat-st-manage-BL31-FCONF-load_info-struct.patch \
	file://0106-feat-st-use-stm32_get_otp_value_from_idx-in-BL31.patch \
	file://0107-feat-st-update-platform-STM32MP2.patch \
	file://0108-feat-stm32mp25-fdts-add-fw-config-file.patch \
	file://0109-feat-fdts-add-stm32mp257f-dk-board-support.patch \
	file://0110-feat-stm32mp2-add-RIF-dt-binding-defines.patch \
	file://0111-feat-fdts-add-RISAF-nodes-for-STM32MP25.patch \
	file://0112-feat-st-drivers-add-RISAF-driver.patch \
	file://0113-feat-stm32mp2-enable-RISAF-driver.patch \
	file://0114-feat-stm32mp2-prepare-DDR-secure-area-encryption.patch \
	file://0115-feat-st-sdmmc2-set-FIFO-size-to-1024-on-STM32MP25.patch \
	file://0116-feat-st-fmc-make-the-reset-optional.patch \
	file://0117-feat-st-fmc-update-the-driver-to-support-STM32MP25.patch \
	file://0118-feat-stm32mp25-fdts-add-FMC2-support.patch \
	file://0119-feat-stm32mp2-add-support-for-SPI-NAND-raw-NAND-boot.patch \
	file://0120-feat-stm32mp2-add-OSPI-support.patch \
	file://0121-feat-stm32mp25-fdts-add-OSPI-support.patch \
	file://0122-feat-mtd-add-dirmap_read-callback.patch \
	file://0123-feat-spi-nand-use-spi_mem_dirmap_read.patch \
	file://0124-feat-mtd-spi_nor-use-spi_mem_dirmap_read.patch \
	file://0125-feat-st-spi-add-dirmap_read-support.patch \
	file://0126-feat-st-spi-manage-multiple-resets.patch \
	file://0127-feat-mtd-spi_mem-add-octal-mode-support.patch \
	file://0128-feat-st-spi-add-octal-mode-support.patch \
	file://0129-feat-mtd-spi_nor-add-octal-read-commands.patch \
	file://0130-feat-stm32mp25-fdts-add-RNG-node.patch \
	file://0131-feat-stm32mp2-add-HASH-and-RNG-compilation.patch \
	file://0132-feat-stm32mp2-update-boot-API-file.patch \
	file://0133-feat-stm32mp2-fdts-add-nvmem_layout-OTP-config.patch \
	file://0134-feat-stm32mp2-get-SoC-part-number-from-OTP.patch \
	file://0135-feat-stm32mp2-add-NAND-OTP-parsing.patch \
	file://0136-feat-stm32mp25-fdts-add-DDRCTRL-and-DDRPHY-settings-.patch \
	file://0137-feat-st-ddr-add-STM32MP2-driver-template.patch \
	file://0138-feat-stm32mp2-add-helper-to-get-DDRDBG-base-address.patch \
	file://0139-feat-st-ddr-add-self-refresh-sequences-for-STM32MP2.patch \
	file://0140-feat-st-ddr-add-STM32MP2-DDRCTRL-management.patch \
	file://0141-feat-stm32mp2-introduce-DDR-type-compilation-flags.patch \
	file://0142-feat-st-ddr-add-STM32MP2-PHY-driver.patch \
	file://0143-feat-st-ddr-add-user-input-mode_register-and-swizzle.patch \
	file://0144-feat-st-ddr-construct-firmware-binaries.patch \
	file://0145-feat-stm32mp2-enable-DDR-PHY-driver.patch \
	file://0146-feat-st-ddr-fill-PHY-user-input-structures-with-DT.patch \
	file://0147-feat-stm32mp2-manage-DDR-FW-via-FIP.patch \
	file://0148-feat-st-ddr-adapt-binary-and-message-block-loads.patch \
	file://0149-feat-stm32mp2-save-restore-DDR-PHY-training-results-.patch \
	file://0150-refactor-st-ddr-phy-remove-unused-timing-group-regis.patch \
	file://0151-fix-st-ddr-manage-quasi-dynamic-register-modificatio.patch \
	file://0152-feat-stm32mp2-pen-holding-for-core-1.patch \
	file://0153-feat-st-ddr-add-firmware-completion-wait-procedure.patch \
	file://0154-feat-st-ddr-implement-phy-error-management.patch \
	file://0155-refactor-st-update-DDR-mapping.patch \
	file://0156-feat-st-fmc-add-RIF-support.patch \
	file://0157-feat-st-initialize-clocks-in-BL31.patch \
	file://0158-feat-st-add-a-helper-to-get-OSPI-memory-mapped-size.patch \
	file://0159-refactor-st-spi-move-on-IOM-bindings.patch \
	file://0160-refactor-stm32mp2-fdts-move-on-IOM-bindings.patch \
	file://0161-refactor-mtd-update-NOR-bank-management.patch \
	file://0162-feat-mtd-add-4-bytes-address-opcodes-for-NOR.patch \
	file://0163-feat-stm32mp2-use-4-bytes-fast-read-opcode.patch \
	file://0164-feat-fdts-add-UART-and-I2C-nodes-for-STM32MP251.patch \
	file://0165-feat-stm32mp2-syscfg-Add-IO-compensation-handling.patch \
	file://0166-feat-stm32mp2-pwr-Add-PWR-driver-for-STM32MP2.patch \
	file://0167-feat-stm32mp2-enable-watchdog-driver.patch \
	file://0168-feat-fdts-add-watchdog-support-for-STM32MP2.patch \
	file://0169-feat-stm32mp2-prepare-PSCI-integration.patch \
	file://0170-feat-stm32mp2-implement-CPU-standby.patch \
	file://0171-feat-stm32mp2-print-board-info.patch \
	file://0172-feat-stm32mp2-add-UART-driver-for-programmer.patch \
	file://0173-feat-stm32mp2-enable-DDR-driver.patch \
	file://0174-feat-stm32mp2-enable-PMIC-driver.patch \
	file://0175-feat-stm32mp2-add-BKPSRAM-base-address.patch \
	file://0176-feat-fdts-add-DDR4-files-for-STM32MP2.patch \
	file://0177-feat-fdts-add-LPDDR4-files-for-STM32MP2.patch \
	file://0178-fix-st-ddr-phy-disable-simulation-options-for-traini.patch \
	file://0179-fix-st-ddr-phy-adjust-phyvref-for-DDR3.patch \
	file://0180-fix-st-ddr-stm32mp2-simplify-reset-and-sysconf-seque.patch \
	file://0181-fix-st-ddr-phy-Set-DfiMode-in-LPDDR4.patch \
	file://0182-feat-st-fmc-reset-FMC2-if-CFGR-access-is-allowed.patch \
	file://0183-feat-st-usb-add-USB-DWC3-driver.patch \
	file://0184-fix-drivers-usb-Remove-packet-splitting-inside-usb-c.patch \
	file://0185-fix-drivers-usb-Call-ep0_out_start-only-for-EP0_OUT.patch \
	file://0186-feat-stm32mp2-fdts-add-package-unique-device-id-in-S.patch \
	file://0187-feat-stm32mp2-add-define-for-device-unique-id-access.patch \
	file://0188-feat-stm32mp1-add-stm32_get_uid_otp.patch \
	file://0189-feat-st-update-stm32cubeprogrammer-API.patch \
	file://0190-feat-stm32mp2-add-support-for-minimal-FIP-with-only-.patch \
	file://0191-feat-stm32mp2-generate-FIP-for-DDR-initialization.patch \
	file://0192-feat-stm32mp2-add-STM32MP_USB_PROGRAMMER-support.patch \
	file://0193-refactor-st-bsec-improve-BSEC-driver.patch \
	file://0194-refactor-st-bsec-add-bsec_get_secure_state.patch \
	file://0195-refactor-st-bsec-rename-defines-for-BSEC_OTP_STATUS.patch \
	file://0196-refactor-st-bsec-remove-unused-defines-BSEC_MODE_.patch \
	file://0197-feat-stm32mp1-fdts-change-name-of-encrypted-key-OTP.patch \
	file://0198-feat-st-bsec-Add-support-of-BSEC_HARDWARE_KEY-for-ST.patch \
	file://0199-refactor-st-bsec-update-bsec_check_nsec_access_right.patch \
	file://0200-refactor-st-bsec-remove-bsec_otp_lock.patch \
	file://0201-refactor-st-bsec-improve-BSEC-API.patch \
	file://0202-refactor-st-bsec-remove-bsec_get_base-function.patch \
	file://0203-refactor-st-bsec-move-defines-in-driver.patch \
	file://0204-refactor-st-bsec-add-otp_bit_mask.patch \
	file://0205-refactor-st-bsec-remove-bsec_read_scratch.patch \
	file://0206-feat-stm32mp2-reserve-the-first-4KB-of-SRAM1-for-BSE.patch \
	file://0207-fix-stm32mp2-DDR-FW-management-via-FIP.patch \
	file://0208-feat-stm32mp2-fdts-change-name-of-OTP-part_number_ot.patch \
	file://0209-feat-stm32mp2-fdts-add-package-otp-in-STM32MP251.patch \
	file://0210-feat-stm32mp2-display-the-STM32MP25x-package-in-SoC-.patch \
	file://0211-feat-stm32mp2-add-RIFSC-RISAB-protection-for-USB3DR.patch \
	file://0212-fix-st-ddr-add-dynamic-pllbypass-DDRDBG-configuratio.patch \
	file://0213-fix-st-ddr-phy-adjust-phyvref-for-DDR4.patch \
	file://0214-fix-fdts-ddr-add-phyvref-and-sequencectrl-for-STM32M.patch \
	file://0215-fix-st-ddr-phy-add-phyvref-and-sequencectrl-advanced.patch \
	file://0216-feat-st-add-interface-to-get-otp-from-phandle.patch \
	file://0217-feat-st-bsec-add-the-write-otp-function-support-in-B.patch \
	file://0218-feat-st-add-a-provisioning-mode-to-manage-shadow-OTP.patch \
	file://0219-feat-fdts-add-hconf1-OTP-reference-for-stm32mp251.patch \
	file://0220-feat-stm32mp2-pwr-Log-VRSEL-not-correctly-set.patch \
	file://0221-fix-st-spi-enable-delay-block-bypass.patch \
	file://0222-fix-st-spi-enable-SSHIFT.patch \
	file://0223-fix-st-spi-always-check-SR_TCF-flags-in-stm32_omi_wa.patch \
	file://0224-fix-stm32mp2-add-quad-SPI-NOR-configuration.patch \
	file://0225-feat-stm32mp1-rework-SVC-services.patch \
	file://0226-feat-stm32mp2-add-common-SMC-runtime-services.patch \
	file://0227-feat-stm32mp2-add-a-runtime-service-for-STGEN-config.patch \
	file://0228-feat-fdts-add-stm32mp25-sdmmc-pins-definitions.patch \
	file://0229-feat-stm32mp25-fdts-add-sdmmc-node-for-STM32MP257F-E.patch \
	file://0230-feat-stm32mp2-fdts-add-UART-console-on-stm32mp257f-e.patch \
	file://0231-feat-fdts-add-clock-tree-for-STM32MP257F-EV.patch \
	file://0232-feat-fdts-add-default-hconf1-OTP-value-for-stm32mp25.patch \
	file://0233-feat-fdts-add-eMMC-node-on-stm32mp257f-ev.patch \
	file://0234-feat-stm32mp2-fdts-add-I2C7-pin-muxing.patch \
	file://0235-feat-fdts-add-OSPI-muxing.patch \
	file://0236-feat-fdts-add-OSPI-nodes-on-eval-board.patch \
	file://0237-feat-st-clock-add-init-of-STM32MP2-DDR-sub-system.patch \
	file://0238-fix-st-usb-fix-issues-with-usb-stop-and-usb-start-co.patch \
	file://0239-feat-st-rif-enforce-encryption-control-on-RISAF-conf.patch \
	file://0240-feat-stm32mp2-add-BL31-device-tree-support.patch \
	file://0241-feat-st-add-an-API-to-retrieve-STM32-image-header.patch \
	file://0242-refactor-stm32mp2-unmap-BL2-DT-area.patch \
	file://0243-refactor-st-update-test-for-closed-chip.patch \
	file://0244-feat-stm32mp2-check-if-chip-is-in-closed-state.patch \
	file://0245-feat-stm32mp2-fdts-add-HASH-PKA-and-SAES.patch \
	file://0246-feat-stm32mp2-map-SRAM2-for-MbedTLS-heap.patch \
	file://0247-feat-st-manage-BL31-certificates.patch \
	file://0248-feat-stm32mp2-add-DDR-firmware-OID.patch \
	file://0249-feat-stm32mp2-manage-PKH-OTP.patch \
	file://0250-feat-stm32mp2-update-image-IDs.patch \
	file://0251-feat-stm32mp2-configure-cert_tool-for-new-images.patch \
	file://0252-feat-stm32mp1-add-PDEF_EXTS-management.patch \
	file://0253-feat-stm32mp2-fdts-enable-HASH-PKA-RNG-and-SAES-for-.patch \
	file://0254-feat-stm32mp2-fdts-update-DT-for-TBBR.patch \
	file://0255-feat-stm32mp2-add-support-for-trusted-boot.patch \
	file://0256-feat-stm32mp2-add-BL31-BL32-encryption-support.patch \
	file://0257-feat-stm32mp2-fdts-add-oem_fip_enc_key-mapping.patch \
	file://0258-refactor-stm32mp2-use-TOOL_ADD_IMG-for-DDR-FW.patch \
	file://0259-feat-stm32mp2-add-trusted-boot-for-serial-boot-devic.patch \
	file://0260-feat-st-get-encryption-key-info-from-DT.patch \
	file://0261-feat-stm32mp2-save-encryption-key-info-before-unmapp.patch \
	file://0262-feat-stm32mp2-add-trace-for-SoC-revision-B.patch \
	file://0263-refactor-st-ddr-stm32mp2-align-restore-refresh-on-le.patch \
	file://0264-refactor-st-ddr-stm32mp2-extend-controller-activatio.patch \
	file://0265-fix-st-ddr-stm32mp2-save-self-refresh-mode-after-eac.patch \
	file://0266-feat-st-ddr-stm32mp2-implement-software-self-refresh.patch \
	file://0267-feat-stm32mp2-add-RETRAM-map-unmap-capability.patch \
	file://0268-feat-st-ddr-stm32mp2-add-RETRAM-dynamic-mmap-during-.patch \
	file://0269-feat-st-ddr-stm32mp2-set-retention-register-in-RETRA.patch \
	file://0270-feat-stm32mp2-implement-is_wakeup_from_standby-servi.patch \
	file://0271-feat-st-ddr-stm32mp2-implement-standby-software-self.patch \
	file://0272-fix-st-ddr-stm32mp2-ensure-correct-LPDDR4-self-refre.patch \
	file://0273-refactor-st-ddr-stm32mp2-rename-self-refresh-exit-fu.patch \
	file://0274-feat-st-pmic-add-STPMIC2-driver.patch \
	file://0275-feat-stm32mp2-handle-DDR-power-supplies.patch \
	file://0276-feat-stm32mp2-add-STPMIC2-driver-support.patch \
	file://0277-feat-stm32mp2-temporary-workaround-LDO5-current-limi.patch \
	file://0278-feat-fdts-describe-stpmic2-power-supplies.patch \
	file://0279-feat-stm32mp2-increase-BL2-size.patch \
	file://0280-feat-stm32mp2-reduce-BL2-size-for-non-trusted-boot.patch \
	file://0281-feat-stm32mp2-syscfg-Add-delay-block-management-for-.patch \
	file://0282-feat-st-spi-add-OSPI-calibration.patch \
	file://0283-feat-stm32mp25-fdts-add-SD-card-supplies-on-eval-boa.patch \
	file://0284-feat-stm32mp25-fdts-add-eMMC-supplies-on-eval-board.patch \
	file://0285-feat-stm32mp2-fdts-add-firewall-nodes-in-fw-config.patch \
	file://0286-feat-st-rif-manage-encryption-with-firmware-configur.patch \
	file://0287-docs-changelog-reorder-ST-drivers-scopes.patch \
	file://0288-docs-changelog-add-st-rif-scope.patch \
	file://0289-feat-stm32mp2-handle-CPU-off-of-core-0.patch \
	file://0290-feat-stm32mp2-add-support-for-Cortex-A35-cluster-res.patch \
	file://0291-feat-stm32mp2-add-stm32mp_gic_cpuif_enable-disable.patch \
	file://0292-feat-stm32mp2-remove-stm32_node_hw_state.patch \
	file://0293-refactor-stm32mp2-load-fw-config-at-the-beginning-of.patch \
	file://0294-feat-docs-add-github-links.patch \
	file://0295-feat-stm32mp2-fdts-update-SoC-device-tree.patch \
	file://0296-feat-stm32mp2-save-a-copy-of-STM32-header.patch \
	file://0297-feat-stm32mp2-update-memory-mapping.patch \
	file://0298-feat-st-add-support-for-external-device-tree-files.patch \
	file://0299-feat-stm32mp2-add-external-DT-management.patch \
	file://0300-feat-fdt-wrappers-add-function-to-read-uint64-with-d.patch \
	file://0301-fix-st-support-device-tree-DDR-sizes-higher-than-16G.patch \
	file://0302-fix-st-change-method-to-get-GIC-base-addresses.patch \
	file://0303-fix-st-add-64-bit-support-on-GIC-base-address.patch \
	file://0304-fix-st-ddr-remove-typedefs.patch \
	file://0305-refactor-stm32mp2-fdts-rework-fw-config-files.patch \
	file://0306-feat-fdts-rename-STM32MP257F-EV-into-STM32MP257F-EV1.patch \
	file://0307-feat-stm32mp2-add-a-low-power-context.patch \
	file://0308-feat-stm32mp2-use-RNG-for-DDR-encryption-key.patch \
	file://0309-feat-stm32mp2-fdts-update-compatible-string-for-watc.patch \
	file://0310-feat-stm32mp2-update-compatible-string-for-watchdog.patch \
	file://0311-feat-psci-update-PSCI_MAX_PWR_LVL-for-extented-State.patch \
	file://0312-refactor-st-move-FWU-functions-to-common-code.patch \
	file://0313-refactor-st-move-FWU-support-to-common-code.patch \
	file://0314-refactor-st-move-FWU-metadata-json-file-to-common-pa.patch \
	file://0315-feat-stm32mp2-add-FWU-support.patch \
	file://0316-fix-stm32mp2-syscfg-Add-delay-block-stop-API.patch \
	file://0317-fix-st-spi-disable-the-delay-block-before-the-calibr.patch \
	file://0318-feat-st-clock-add-stm32mp2-pll1-functions-for-stm32m.patch \
	file://0319-feat-st-ddr-phy-release-upgrade-firmware.patch \
	file://0320-feat-st-ddr-phy-release-upgrade-phyinit.patch \
	file://0321-fix-st-ddr-preserve-DDR-sharing-in-driver.patch \
	file://0322-feat-st-drivers-stm32_iwdg-start-the-watchdog-on-sta.patch \
	file://0323-feat-stm32mp2-fix-macros-for-watchdog-s-OTP.patch \
	file://0324-feat-stm32mp2-add-watchdog-support.patch \
	file://0325-feat-stm32mp25-fdts-add-iwdg1-on-eval-board.patch \
	file://0326-refactor-st-clock-data-size-optimization.patch \
	file://0327-refactor-st-clock-data-size-optimization.patch \
	file://0328-refactor-st-clock-code-size-optimization.patch \
	file://0329-refactor-st-clock-code-size-optimization.patch \
	file://0330-refactor-st-clock-use-STM32_GATE-instead-GATE-for-ST.patch \
	file://0331-refactor-st-clock-optimize-clock-ops-management.patch \
	file://0332-feat-st-spi-allow-to-sample-later-the-data.patch \
	file://0333-feat-mtd-add-hyperflash-framework.patch \
	file://0334-feat-st-spi-add-hyperflash-support.patch \
	file://0335-feat-stm32mp2-add-hyperflash-support.patch \
	file://0336-feat-optee-add-a-new-function-opteed_restore.patch \
	file://0337-refactor-stm32mp2-configure-clocks-and-UART-earlier-.patch \
	file://0338-feat-stm32mp2-check-arg0-in-bl31_early_platform_setu.patch \
	file://0339-feat-stm32mp2-add-support-for-PSCI_OS_INIT_MODE.patch \
	file://0340-feat-stm32mp2-keep-RETRAM-in-Standby-mode.patch \
	file://0341-feat-psci-export-psci_set_target_local_pwr_states.patch \
	file://0342-refactor-st-ddr-stm32mp2-rename-self-refresh-exit-fu.patch \
	file://0343-refactor-stm32mp2-move-some-functions-in-bl31_plat_a.patch \
	file://0344-feat-stm32mp2-restore-context-after-standby.patch \
	file://0345-fix-stm32mp2-correctly-handle-STANDBY.patch \
	file://0346-refactor-stm32mp2-move-backup-domain-reset-to-a-dedi.patch \
	file://0347-refactor-st-bsec-harmonize-bsec_shadow_read_otp.patch \
	file://0348-feat-stm32mp2-fdts-add-memory-node.patch \
	file://0349-feat-stm32mp2-fdts-update-STM32MP257F-EV1-DT.patch \
	file://0350-feat-stm32mp2-add-plat_my_core_pos.patch \
	file://0351-feat-stm32mp2-disable-unsupported-features.patch \
	file://0352-feat-st-do-not-directly-call-BSEC-function-in-common.patch \
	file://0353-feat-mtd-add-DTR-support-in-spi-mem.patch \
	file://0354-feat-mtd-spi_nor-add-octal-DTR-support.patch \
	file://0355-fix-stm32mp2-multiple-fixes-added-for-DTR-support.patch \
	file://0356-feat-st-spi-multiple-fixes-added-for-DTR-support.patch \
	file://0357-feat-mtd-add-reset-callback.patch \
	file://0358-fix-stm32mp2-flush-data-cache-at-the-end-of-BL2.patch \
	file://0359-feat-stm32mp2-add-IO-exit-API.patch \
	file://0360-feat-stm32mp2-add-IAC-defines.patch \
	file://0361-fix-stm32mp2-rename-some-RIF-macros.patch \
	file://0362-feat-st-drivers-add-RIFSC-driver.patch \
	file://0363-fix-stm32mp2-correct-typo-in-definition-header.patch \
	file://0364-fix-st-usb-optimize-dwc3-structure-size.patch \
	file://0365-feat-stm32mp2-add-DDR-power-init-sequence-for-STM32M.patch \
	file://0366-feat-stm32mp2-add-add-a-function-to-set-ICN-QOS.patch \
	file://0367-refactor-st-clock-rename-USB3DRD.patch \
	file://0368-feat-st-bsec-export-BSEC-function-for-SSP.patch \
	file://0369-feat-st-add-SSP-support-for-STM32CubeProgrammer.patch \
	file://0370-feat-stm32mp1-add-secure-secret-provisioning.patch \
	file://0371-feat-st-update-SSP-for-stm32mp13-platform.patch \
	file://0372-fix-stm32mp1-ssp-improve-SSP-robustness-and-allow-to.patch \
	file://0373-fix-st-fix-the-ssp_otp-nvmem-for-stm32mp13.patch \
	file://0374-feat-stm32mp1-fdts-remove-useless-delete-node-proper.patch \
	file://0375-fix-st-fix-uart-issue-in-SSP-mode.patch \
	file://0376-feat-stm32mp1-fdts-add-sysram-node-for-ssp.patch \
	file://0377-fix-stm32mp1-fix-uart-download-issue-on-console.patch \
	file://0378-fix-stm32mp1-check-for-the-correct-vddcore-regulator.patch \
	file://0379-feat-stm32mp2-put-back-core-1-in-wfi-after-debugger-.patch \
	file://0380-feat-stm32mp2-invalidate-cache-after-BL2-DT-unmap.patch \
	file://0381-refactor-stm32mp2-update-IMAGE_IDs.patch \
	file://0382-fix-stm32mp2-increase-BL31-size.patch \
	file://0383-fix-st-clock-make-_clk_get_ops-static.patch \
	file://0384-refactor-st-clock-move-stm32mp1_clk_rcc_regs_-lock.patch \
	file://0385-fix-st-clock-make-ops_array_mp13-static.patch \
	file://0386-fix-st-clock-make-ops_array_mp25-static.patch \
	file://0387-fix-stm32mp2-set-some-PM-functions-static.patch \
	file://0388-refactor-stm32mp1-create-reset_backup_domain-functio.patch \
	file://0389-feat-stm32mp2-set-BL2_IN_XIP_MEM.patch \
	file://0390-feat-st-introduce-EARLY-traces-macros.patch \
	file://0391-feat-stm32mp2-add-debug-traces-in-BL31.patch \
	file://0392-feat-st-clock-use-early-traces.patch \
	file://0393-feat-st-bsec-use-early-traces.patch \
	file://0394-fix-st-gpio-configure-each-GPIO-mux-as-secure-for-MP.patch \
	file://0395-docs-dt-bindings-add-DDR-device-tree-bindings-used-o.patch \
	file://0396-feat-stm32mp2-tune-interconnect-bandwidth.patch \
	file://0397-fix-psci-fix-power-level-for-CPU-off-with-OSI.patch \
	file://0398-refactor-st-clock-support-deactivated-STGEN-in-stm32.patch \
	file://0399-feat-stm32mp2-save-gicv2-configuration-for-STOP2-mod.patch \
	file://0400-fix-psci-fix-parent_idx-in-psci_validate_state_coord.patch \
	file://0401-fix-psci-fix-parent-parsing-in-psci_is_last_cpu_to_i.patch \
	file://0402-feat-stm32mp2-add-function-plat_get_target_pwr_state.patch \
	file://0403-feat-psci-fix-psci_update_req_local_pwr_states.patch \
	file://0404-refactor-st-clock-remove-unused-clk-function-in-API.patch \
	file://0405-feat-st-ddr-add-DDR-clock-init-function.patch \
	file://0406-refactor-st-clock-remove-DDR-clock-init.patch \
	file://0407-feat-stm32mp2-enable-DDR-sub-system-clock.patch \
	file://0408-feat-stm32mp2-introduce-STM32MP_M33_TDCID-flag.patch \
	file://0409-feat-stm32mp2-stub-DDR-configuration-when-not-TDCID.patch \
	file://0410-feat-stm32mp2-stub-some-features-when-not-TDCID.patch \
	file://0411-feat-stm32mp2-add-OTP-functions-M33-TDCID.patch \
	file://0412-feat-st-clock-stub-some-registers-access-when-not-TD.patch \
	file://0413-feat-psci-add-PLAT_MIN_SUSPEND_PWR_LVL.patch \
	file://0414-feat-stm32mp2-verify-power-mode-for-suspend-request.patch \
	file://0415-feat-gicv2-add-gicv2_distif_save-restore-functions.patch \
	file://0416-feat-st-add-stm32mp_gic_save-resume-functions.patch \
	file://0417-feat-stm32mp2-display-pending-IAC-in-BL2-entry.patch \
	file://0418-feat-fdts-add-support-for-STM32MP257F-DK.patch \
	file://0419-docs-changelog-add-stm32mp25-fdts-scope.patch \
	file://0420-feat-stm32mp2-increase-STM32MP_HW_CONFIG_MAX_SIZE.patch \
	file://0421-feat-stm32mp1-fdts-remove-RTC-clock-configuration.patch \
	file://0422-feat-stm32mp1-check-the-backup-ram-access.patch \
	file://0423-feat-stm32mp15-allow-Backup-SRAM-access-after-tamper.patch \
	file://0424-fix-stm32mp2-update-boot-API-header-version.patch \
	file://0425-fix-stm32mp1-remove-unnecessary-assert-on-GPIO_BANK_.patch \
	file://0426-fix-stm32mp2-remove-unnecessary-assert-on-GPIO_BANK_.patch \
	file://0427-feat-fdts-enable-sdmmc2-for-eMMC-on-STM32MP257F-DK.patch \
	file://0428-feat-fdts-activate-IWDG1-on-STM32MP257F-DK.patch \
	file://0429-feat-bl-align-DATA-section-end-on-2-bytes.patch \
	file://0430-feat-stm32mp2-Mask-potential-tamper-during-FSBL-exec.patch \
	file://0431-feat-stm32mp2-fdts-add-nvram-NVMEM-node-under-tamp-i.patch \
	file://0432-feat-stm32mp13-fdts-add-nvram-NVMEM-node-under-tamp-.patch \
	file://0433-feat-stm32mp15-fdts-add-nvram-NVMEM-node-under-tamp-.patch \
	file://0434-feat-st-nvmem-add-nvmem-framework.patch \
	file://0435-feat-st-add-support-for-TAMP-backup-registers.patch \
	file://0436-feat-stm32mp2-initialize-TAMP-Backup-Registers-for-B.patch \
	file://0437-feat-st-use-NVMEM-framework-instead-of-direct-reg-ac.patch \
	file://0438-refactor-st-ddr-use-enum-in-ddrphy_phyinit_softsetmb.patch \
	file://0439-refactor-st-ddr-reduce-error-message.patch \
	file://0440-feat-stm32mp2-limit-the-max-size-of-BL31.patch \
	file://0441-feat-stm32mp2-stub-PM-code-in-serial-boot.patch \
	file://0442-feat-stm32mp1-stub-PM-code-in-serial-boot.patch \
	file://0443-feat-stm32mp2-reduce-BL2-size-for-serial-boot.patch \
	file://0444-fix-stm32mp2-add-INIT_UNUSED_NS_EL2-flag.patch \
	file://0445-fix-stm32mp2-correct-early-crash-console-init.patch \
	file://0446-revert-feat-psci-export-psci_set_target_local_pwr_st.patch \
	file://0447-fix-psci-add-optional-pwr_domain_validate_suspend-to.patch \
	file://0448-fix-stm32mp2-update-pwr_domain_suspend.patch \
	file://0449-fix-stm32mp1-stub-some-code-for-SSP.patch \
	file://0450-fix-stm32mp2-properly-check-err-values.patch \
	file://0451-refactor-stm32mp2-move-cache-invalidation.patch \
	file://0452-feat-stm32mp2-map-DDR-part-non-secure-when-M33-is-TD.patch \
	file://0453-feat-stm32mp2-skip-ICN-configuration-if-M33-is-TDCID.patch \
	file://0454-feat-stm32mp2-remove-RISAF-config-for-M33-TDCID.patch \
	file://0455-feat-stm32mp2-add-intrusion-alert-upon-tamper-event-.patch \
	file://0456-feat-stm32mp1-add-intrusion-alert-upon-tamper-event-.patch \
	file://0457-fix-stm32mp2-fdts-remove-unused-macro-DDR_SIZE.patch \
	file://0458-refactor-st-change-suffixes-for-SYSCFG-functions.patch \
	file://0459-fix-stm32mp2-update-print_reset_reason.patch \
	file://0460-feat-st-ddr-improve-quasi-dynamic-register-init-for-.patch \
	file://0461-fix-st-ddr-make-systematic-tests-aarch-generic.patch \
	file://0462-refactor-stm32mp2-add-DDR-FW-path-macro.patch \
	file://0463-refactor-stm32mp2-move-DDR-PHY-FW-files-in-sub-direc.patch \
	file://0464-feat-st-crypto-check-if-SAES-is-already-initialized.patch \
	file://0465-feat-stm32mp1-derivating-MCE-key-from-HUK.patch \
	file://0466-feat-stm32mp2-derivating-DDRCryp-encryption-key-from.patch \
	file://0467-feat-st-ddr-add-ddr_sub_system_clk_off-for-STM32MP2.patch \
	file://0468-fix-stm32mp2-correct-stm32_system_off.patch \
	file://0469-feat-stm32mp2-adjust-DDR4-init-delays.patch \
	file://0470-feat-stm32mp2-handle-st-mask-reset-property.patch \
	file://0471-feat-stm32mp1-handle-st-mask-reset-property.patch \
	file://0472-refactor-st-pmic-remove-useless-structure-fields.patch \
	file://0473-refactor-st-drivers-remove-useless-structure-fields-.patch \
	file://0474-refactor-stm32mp2-pwr-remove-useless-structure-field.patch \
	file://0475-refactor-st-clock-remove-unused-struct.patch \
	file://0476-refactor-st-use-c-to-display-board-info.patch \
	file://0477-refactor-stm32mp2-remove-unused-variable.patch \
	file://0478-refactor-stm32mp2-remove-ddr_type-from-pmic_ddr_powe.patch \
	file://0479-fix-stm32mp2-correct-NAND-error-message.patch \
	file://0480-refactor-stm32mp2-remove-firewall-file.patch \
	file://0481-refactor-stm32mp2-revisit-stm32mp2_syscfg_get_mm_siz.patch \
	file://0482-feat-stm32mp1-only-fuse-monotonic-counter-on-closed-.patch \
	file://0483-refactor-stm32mp2-cosmetic-updates-in-platform.mk.patch \
	file://0484-refactor-st-remove-metadata-compilation-dependency.patch \
	file://0485-feat-st-add-a-compilation-rule-for-metadata.patch \
	file://0486-feat-efi-add-metadata-GUID-define.patch \
	file://0487-feat-st-add-GUID-support-for-metadata-partition-sele.patch \
	file://0488-feat-stm32image-add-header-version-2.3-support.patch \
	file://0489-docs-stm32mp2-correct-STM32MP2-frequencies.patch \
	file://0490-docs-stm32mp2-introduce-new-STM32MP21-family.patch \
	file://0491-feat-stm32mp2-include-dedicated-clocks-and-RCC-heade.patch \
	file://0492-feat-st-clock-add-STM32MP2-variants-compliance-in-dr.patch \
	file://0493-feat-stm32mp21-fdts-add-SoC-DT-files.patch \
	file://0494-feat-stm32mp21-fdts-add-pinctrl-DT-file.patch \
	file://0495-feat-stm32mp23-fdts-add-pinctrl-DT-file.patch \
	file://0496-feat-stm32mp21-manage-STM32MP21-DT-overlays.patch \
	file://0497-feat-stm32mp23-manage-STM32MP23-DT-overlays.patch \
	file://0498-feat-stm32mp21-fdts-add-fw-config-file.patch \
	file://0499-feat-stm32mp23-fdts-add-fw-config-file.patch \
	file://0500-feat-stm32mp21-update-SRAM1-and-RETRAM-base-address.patch \
	file://0501-feat-stm32mp21-remove-GPIOJ-and-GPIOK.patch \
	file://0502-feat-stm32mp21-add-PWR-registers-file.patch \
	file://0503-feat-stm32mp21-disable-PWR_CPU3CR-and-PWR_D3CR-acces.patch \
	file://0504-feat-stm32mp21-disable-RCC_C1P1RSTCSETR-access-on-ST.patch \
	file://0505-feat-st-bsec3-add-STM32MP21-version-support.patch \
	file://0506-feat-st-bsec-update-OTPCR-masks-for-STM32MP21.patch \
	file://0507-feat-stm32mp21-update-revision-A-ID.patch \
	file://0508-feat-stm32mp21-update-STM32-header-size-for-STM32MP2.patch \
	file://0509-docs-changelog-add-subsections-for-STM32MP2.patch \
	file://0510-docs-stm32mp2-introduce-new-STM32MP23-family.patch \
	file://0511-feat-stm32mp21-introduce-new-STM32MP21-flag.patch \
	file://0512-feat-stm32mp23-introduce-new-STM32MP23-flag.patch \
	file://0513-feat-stm32mp21-update-boot-API-header-version.patch \
	file://0514-feat-stm32mp21-add-SoC-part-numbers.patch \
	file://0515-feat-stm32mp23-add-SoC-part-numbers.patch \
	file://0516-feat-stm32mp2-define-UART8-and-UART9-under-STM32MP25.patch \
	file://0517-feat-stm32mp25-put-PKG-numbers-under-flag.patch \
	file://0518-feat-stm32mp21-add-clock-and-reset-bindings.patch \
	file://0519-feat-stm32mp23-add-clock-and-reset-bindings.patch \
	file://0520-feat-stm32mp21-add-RCC-registers-file.patch \
	file://0521-feat-stm32mp21-no-GPU-BW-limiter-disable-on-STM32MP2.patch \
	file://0522-feat-stm32mp21-no-IWDG5-reset-on-STM32MP21.patch \
	file://0523-feat-stm32mp23-fdts-add-SoC-DT-files.patch \
	file://0524-feat-st-rif-add-RISAF-MCE-support-for-STM32MP21.patch \
	file://0525-feat-stm32mp2-manage-RISAF-MCE-key-for-STM32MP21.patch \
	file://0526-feat-st-usb-enable-USBOTG-DFU-for-STM32MP21.patch \
	file://0527-feat-stm32mp21-enable-USBOTG-DFU.patch \
	file://0528-fix-fdts-change-PLL-node-name-in-STM32MP25-clock-tre.patch \
	file://0529-feat-stm32mp21-disable-PWR_CPU3D3SR-access-on-STM32M.patch \
	file://0530-feat-stm32mp21-disable-PWR_D3CR-access-on-STM32MP21.patch \
	file://0531-refactor-st-rif-cleanup-RIFSC-IP-configuration.patch \
	file://0532-feat-stm32mp21-add-RIFSC-IDs-bindings.patch \
	file://0533-feat-stm32mp23-add-RIFSC-IDs-bindings.patch \
	file://0534-feat-st-rif-add-STM32MP2x-support-in-RIFSC-driver.patch \
	file://0535-feat-stm32mp2-add-RIFSC-USB-configuration-for-varian.patch \
	file://0536-feat-st-ddr-add-quasi-dynamic-register-for-STM32MP21.patch \
	file://0537-feat-stm32mp21-fdts-add-STM32MP215F-DK-board.patch \
	file://0538-feat-stm32mp23-fdts-add-STM32MP235F-DK-board.patch \
	file://0539-fix-stm32mp2-keep-ECSDA-key-and-signature-definition.patch \
	file://0540-fix-st-crypto-adapt-kshareid-values-for-STM32MP25.patch \
	file://0541-feat-stm32-rng-add-multi-instance-support-in-RNG-dri.patch \
	file://0542-refactor-stm32mp25-fdts-rename-IOM-EVAL-pins-muxing-.patch \
	file://0543-feat-st-spi-Add-the-support-of-the-SFDP-calibration.patch \
	file://0544-feat-st-pmic-support-st-regulator-sink-source.patch \
	file://0545-feat-stm32mp25-fdts-add-sink-source-for-LDO3-with-DD.patch \
	file://0546-feat-st-regulator-support-regulator_set_voltage-for-.patch \
	file://0547-docs-dt-bindings-add-DDR-supply-in-STM32MP2-device-t.patch \
	file://0548-feat-stm32mp25-fdts-add-DDR-power-supplies.patch \
	file://0549-feat-stm32mp2-access-to-DDR-regulators-by-supply-nam.patch \
	file://0550-feat-stm32mp2-add-DDR3-platform-power-functions.patch \
	file://0551-feat-stm32mp25-fdts-add-ramp-delay-on-ddr-supply.patch \
	file://0552-feat-stm32mp2-regulator-enable-ramp-delay-for-DDR-re.patch \
	file://0553-fix-st-gpio-configure-each-GPIO-mux-as-secure-for-ST.patch \
	file://0554-fix-st-allow-several-call-of-stm32cubeprog_uart_load.patch \
	file://0555-feat-stm32mp2-add-UART-Programmer-support.patch \
	file://0556-fix-stm32mp2-fix-the-LP-Stop2-and-LPLV-Stop2.patch \
	file://0557-feat-stm32mp2-add-fdt-address-in-low-power-context.patch \
	file://0558-feat-stm32mp2-optimize-the-wake-up-time-for-low-powe.patch \
	file://0559-feat-st-ddr-improve-sequence-of-self-refresh-exit.patch \
	file://0560-feat-fdts-add-UART-nodes-for-STM32MP211.patch \
	file://0561-fix-stm32mp2-increase-BL2-DTB-size.patch \
	file://0562-feat-fwu-update-the-URL-links-for-the-FWU-specificat.patch \
	file://0563-feat-fwu-document-the-config-flag-for-including-imag.patch \
	file://0564-feat-fwu-migrate-FWU-metadata-structure-to-version-2.patch \
	file://0565-feat-fwu-add-a-config-flag-for-including-image-info-.patch \
	file://0566-feat-st-get-the-state-of-the-active-bank-directly.patch \
	file://0567-feat-fwu-modify-the-check-for-getting-the-FWU-bank-s.patch \
	file://0568-feat-fwu-add-some-sanity-checks-for-the-FWU-metadata.patch \
	file://0569-feat-fwu-add-a-function-to-obtain-an-alternate-FWU-b.patch \
	file://0570-feat-st-add-a-function-to-clear-the-FWU-trial-state-.patch \
	file://0571-feat-st-add-logic-to-boot-the-platform-from-an-alter.patch \
	file://0572-style-partition-use-GUID-values-for-GPT-partition-fi.patch \
	file://0573-style-fwu-change-the-metadata-fields-to-align-with-s.patch \
	file://0574-feat-stm32mp2-remove-PM-in-serial-boot.patch \
	file://0575-fix-stm32mp2-add-a-stub-PSCI-ops-structure.patch \
	file://0576-feat-plat-stm32mp2-remove-stm32_iwdg_shadow_update.patch \
	file://0577-fix-stm32mp2-fix-watchdog-support.patch \
	file://0578-feat-st-crypto-add-STM32MP21-SAES-driver-support.patch \
	file://0579-feat-fdts-introduce-STM32MP21-pinctrl-files.patch \
	file://0580-refactor-st-ddr-reduce-DDR-driver-footprint-for-STM3.patch \
	file://0581-refactor-stm32mp1-update-reset_backup_domain-functio.patch \
	file://0582-feat-stm32mp1-add-TAMPER-management-logic-at-bl2-pla.patch \
	file://0583-refactor-stm32mp2-update-reset_backup_domain-functio.patch \
	file://0584-feat-stm32mp2-add-TAMPER-management-logic-at-bl2-pla.patch \
	file://0585-fix-st-clock-adapt-order-of-CSS-on-LSE-and-HSE.patch \
	file://0586-feat-stm32mp1-remove-stop-watchdog-when-going-in-low.patch \
	file://0587-fix-stm32mp2-proper-management-of-platform-flags.patch \
	file://0588-feat-stm32mp2-remove-function-stm32_iwdg_shadow_upda.patch \
	file://0589-feat-st-remove-unused-IWDG-flags.patch \
	file://0590-feat-docs-add-STM32MP2-docs-links.patch \
	file://0591-refactor-stm32mp2-rename-clock-driver.patch \
	file://0592-feat-stm32mp21-fdts-add-support-for-console-for-stm3.patch \
	file://0593-feat-stm32mp21-fdts-add-support-for-watchdog.patch \
	file://0594-feat-stm32mp21-fdts-add-I2C-nodes-for-stm32mp211.patch \
	file://0595-feat-stm32mp21-fdts-add-support-for-I2C3-on-stm32mp2.patch \
	file://0596-feat-stm32mp23-fdts-add-RCC-and-RIF-configuration-fo.patch \
	file://0597-feat-stm32mp2-fdts-remove-the-pins-are-numbered-prop.patch \
	file://0598-refactor-st-clock-remove-useless-LSEDRV_MEDIUM_HIGH-.patch \
	file://0599-fix-dt-bindings-correct-LSEDRV-values.patch \
	file://0600-feat-st-spi-add-OSPI-support-for-MP21.patch \
	file://0601-fix-st-clock-display-proper-PLL-number.patch \
	file://0602-fix-st-clock-display-proper-PLL-number-for-STM32MP13.patch \
	file://0603-feat-stm32mp25-fdts-update-RIF-configuration-for-DK-.patch \
	file://0604-feat-stm32mp25-fdts-update-RIF-configuration.patch \
	file://0605-feat-stm32mp21-add-PKA-node-in-STM32MP21-platforms.patch \
	file://0606-feat-stm32mp21-add-HASH-node-for-STM32MP21.patch \
	file://0607-feat-stm32mp21-enable-crypto-peripherals-on-STM32MP2.patch \
	file://0608-fix-st-ddr-manage-CID-filtering-when-accessing-PWR_C.patch \
	file://0609-feat-fdts-add-sdmmc2-node-for-stm32mp21.patch \
	file://0610-feat-fdts-add-fmc-node-for-stm32mp21.patch \
	file://0611-feat-fdts-add-ospi1-node-for-stm32mp21.patch \
	file://0612-feat-fdts-add-sdmmc2-pins-for-stm32mp21.patch \
	file://0613-fix-stm32mp2-fdts-keep-ommanager-for-hyperflash.patch \
	file://0614-fix-stm32mp2-skip-iac_dump-when-M33-is-TDCID.patch \
	file://0615-fix-stm32mp2-skip-OP-TEE-header-check-if-image-base-.patch \
	file://0616-Revert-feat-stm32mp2-derivating-DDRCryp-encryption-k.patch \
	file://0617-Revert-feat-stm32mp1-derivating-MCE-key-from-HUK.patch \
	file://0618-feat-stm32mp23-fdts-update-STM32MP235F-DK-board.patch \
	file://0619-feat-stm32mp2-implement-new-SoC-revision-ID-system.patch \
	file://0620-feat-st-pmic-add-support-for-STPMIC1L-and-STPMIC2L.patch \
	file://0621-feat-stm32mp1-make-stpmic2-usable-for-STM32MP1.patch \
	file://0622-feat-stm32mp1-update-STPMIC1-driver-to-handle-more-p.patch \
	file://0623-feat-stm32mp1-fdts-add-DDR-power-supplies-descriptio.patch \
	file://0624-feat-stm32mp1-rework-ddr-supplies-handling.patch \
	file://0625-feat-stm32mp21-describe-power-supplies-on-STM32MP215.patch \
	file://0626-feat-fdts-add-stm32mp215f-dk-system-configuration-fi.patch \
	file://0627-feat-stm32mp2-pwr-syscfg-skip-none-existent-STM32MP2.patch \
	file://0628-feat-stm32mp2-add-a-new-stm32mp21-power-compatible.patch \
	file://0629-fix-st-rif-use-clr-set-bit-when-configuring-RIFSC.patch \
	file://0630-feat-st-clk-add-dmb-dsb-in-clock-driver.patch \
	file://0631-fix-st-update-STM32MP2-part-number.patch \
	file://0632-feat-stm32mp2-add-binary-as-payload-to-support-build.patch \
	file://0633-feat-stm32mp25-adapt-authentication-status.patch \
	file://0634-feat-stm32mp2-fdts-add-CRYP1-and-CRYP2-to-mp2-device.patch \
	file://0635-Revert-feat-bl-align-DATA-section-end-on-2-bytes.patch \
	file://0636-fix-dt-bindings-update-STM32MP2-clock-and-reset-bind.patch \
	file://0637-fix-stm32mp2-maintain-LPSRAM1-content-in-standby-mod.patch \
	file://0638-feat-stm32mp1-fdts-configure-only-used-clocks.patch \
	file://0639-feat-st-rework-FWU-to-consider-trial-counter-0-as-un.patch \
	file://0640-feat-stm32mp21-DDR-describe-power-supplies-on-STM32M.patch \
	file://0641-refactor-stm32mp2-remove-NS_SYSRAM.patch \
	file://0642-feat-stm32mp2-use-the-first-half-of-SYSRAM-for-BL31.patch \
	file://0643-feat-stm32mp21-fdts-add-provisioning-node-for-STM32M.patch \
	file://0644-feat-stm32mp21-fdts-add-board-ID-OTP-for-STM32MP215F.patch \
	file://0645-fix-stm32mp1-ssp-fix-minor-issue-in-TFA-SSP.patch \
	file://0646-feat-stm32mp21-fdts-add-SD-card-support-for-stm32mp2.patch \
	file://0647-feat-stm32mp21-fdts-add-eMMC-support-for-stm32mp215f.patch \
	file://0648-feat-st-disable-FWU-on-serial-boot-devices.patch \
	file://0649-fix-stm32mp2-correct-package-types-on-STM32MP25.patch \
	file://0650-feat-stm32mp2-display-package-type-for-STM32MP21.patch \
	file://0651-feat-stm32mp2-display-package-type-for-STM32MP23.patch \
	file://0652-fix-st-crypto-do-not-set-IPRST-if-BUSY-flag-is-prese.patch \
	file://0653-fix-st-gpio-configure-each-GPIO-mux-as-secure-for-ST.patch \
	file://0654-feat-stm32mp2-support-running-M33-for-low-power-mode.patch \
	file://0655-fix-stm32mp2-restore-PLL1-settings-after-STOP2-modes.patch \
	file://0656-feat-st-clock-rename-stm32mp2_a35_ss_on_hsi.patch \
	file://0657-feat-st-clock-force-HSI-for-CA35-bypass-clock-for-lo.patch \
	file://0658-stm32mp2-Call-the-OP-TEE-SPD-cpu-suspend-handler-for.patch \
	file://0659-feat-stm32mp2-add-OTP-mirror-read-code.patch \
	file://0660-fix-stm32mp2-stm32_otp_is_closed_device-should-retur.patch \
	file://0661-feat-stm32mp2-boot-BL33-at-EL2.patch \
	file://0662-feat-st-clk-move-oscillators-ops-from-clk-stm32-core.patch \
	file://0663-feat-stm32mp2-fdts-fix-rcc-support-in-stm32mp251.patch \
	file://0664-fix-st-bootcount-must-be-initialized-outside-the-cas.patch \
	file://0665-refactor-stm32mp2-simplify-STM32MP2-flag-selection-i.patch \
	file://0666-feat-st-crypto-change-RNG-code-to-improve-MISRA-comp.patch \
	file://0667-fix-checkpatch-detect-issues-in-commit-message.patch \
	file://0668-fix-st-ddr-improve-DLL-clock-management-in-self-refr.patch \
	file://0669-feat-stm32mp2-update-BSEC-fuse-map-for-STM32MP21.patch \
	file://0670-feat-st-clk-move-gate_refcounts-check-to-use-UINT8_M.patch \
	file://0671-feat-stm32-rif-improve-peripheral-access-acquisition.patch \
	file://0672-feat-st-introduce-SoC-family-compilation-switch.patch \
	file://0673-fix-stm32-rng-RNG-doesn-t-take-into-account-fully-di.patch \
	file://0674-feat-st-allow-SRAM1-secure-accesses-earlier-in-bl2_e.patch \
	file://0675-Revert-fix-psci-fix-parent-parsing-in-psci_is_last_c.patch \
	file://0676-fix-psci-fix-parent-parsing-in-psci_is_last_cpu_to_i.patch \
	file://0677-fix-stm32mp2-remove-mapping-of-BL2-DT-area.patch \
	file://0678-feat-stm32mp2-change-PKH_OTP-value-for-STM32MP21.patch \
	file://0679-feat-st-crypto-Change-PKA-compatible-name.patch \
	file://0680-feat-fdts-change-PKA-compatible-name.patch \
	file://0681-fix-stm32mp2-enable-trusted-boot-for-STM32MP21.patch \
	file://0682-refactor-stm32mp2-update-authentication-check-for-ST.patch \
	file://0683-fix-stm32mp2-remove-all-set-of-gpio-secure-in-M33TD-.patch \
	file://0684-fix-stm32mp2-add-some-critical-clock-in-M33TD-build.patch \
	file://0685-stm32mp21-check-HWKEY-validity-before-writing-RISAF-.patch \
	file://0686-fix-stm32mp2-mask-potential-tamper-earlier.patch \
	file://0687-feat-dt-bindings-add-declaration-of-RIF_UNUSED.patch \
	file://0688-fix-fdts-set-flexgen-58-to-HSE_KER-for-STM32MP257F-D.patch \
	file://0689-fix-stm32mp2-isolate-STGEN-in-low-power.patch \
	file://0690-feat-stm32mp2-force-autonomous-mode-for-LPSRAM1-2-3-.patch \
	file://0691-fix-st-clock-force-ARM_DIVSEL-for-flexgen63-config-a.patch \
	file://0692-Trace-in-stm32_get_sys_suspend_power_state.patch \
	file://0693-fix-cert-create-add-default-keysize-to-Brainpool-ECD.patch \
	file://0694-fix-st-crypto-check-RNG-seed-error-after-null-data-r.patch \
	file://0695-feat-stm32mp2-improve-BL31-size-management.patch \
	file://0696-fix-stm32mp2-reduce-BL2-size-on-trusted-boot.patch \
	file://0697-fix-st-usb-decrease-log-level-to-info-verbose.patch \
	file://0698-Revert-feat-stm32mp23-add-clock-and-reset-bindings.patch \
	file://0699-fix-stm32mp2-fdts-fix-SDMMC-slew-rate-on-eval-and-dk.patch \
	file://0700-fix-dt-bindings-bad-FLEXGEN-configuration-of-pred-di.patch \
	file://0701-feat-stm32mp2-limit-low-power-mode-when-cortex-M0-is.patch \
	file://0702-feat-stm32mp2-fix-CPU1-wake-up-from-RUN2.patch \
	file://0703-fix-stm32mp2-fdts-fix-SDMMC1-slew-rate-on-eval-and-d.patch \
	file://0704-fix-stm32mp2-fdts-move-stm32mp23-dk-board-on-new-SDM.patch \
	file://0705-fix-stm32mp2-fdts-move-stm32mp25-dk-board-on-new-SDM.patch \
	file://0706-feat-st-clock-force-clock-tree-for-Stop2-low-power-m.patch \
	file://0707-fix-stm32mp2-optimize-the-wake-up-time-for-low-power.patch \
	file://0708-feat-stm32mp2-allow-to-disable-debug.patch \
	file://0709-fix-stm32mp2-restore-STGEN-before-PLL1-settings-afte.patch \
	file://0710-feat-st-clk-add-ck_sys_dbg-clock-for-STM32MP2.patch \
	file://0711-stm32mp2-clear-RCC-C1P1RSTF-flag-after-core-power-on.patch \
	file://0712-feat-stm32mp21-no-Core1-reset-on-STM32MP21.patch \
	file://0713-fix-stm32mp21-remove-C1P1-flag-in-RCC.patch \
	file://0714-feat-stm32mp2-indicate-Core-1-reset-for-all-reset-re.patch \
	file://0715-refactor-stm32mp2-update-display-of-reset-reason.patch \
	file://0716-feat-st-add-stm32mp_uart_console_is_running.patch \
	file://0717-fix-stm32mp2-disable-console-if-necessary-during-LP-.patch \
	file://0718-build-add-no-warn-rwx-segments-when-linking-with-GCC.patch \
	file://0719-feat-stm32mp2-disable-PIE-by-default-on-STM32MP2-pla.patch \
	file://0720-feat-st-update-ST-specific-version.patch \
	file://0721-feat-stm32mp2-fix-shutdown-on-STM32MP21.patch \
	file://0722-fix-stm32mp2-remove-critical-clock-in-M33TD-build.patch \
	file://0723-feat-stm32mp2-support-cortex-M33-as-TDCID-in-STM32MP.patch \
	file://0724-feat-st-clock-test-if-clock-is-already-enabled.patch \
	file://0725-feat-st-clock-do-not-disable-clock-when-M33-is-TDCID.patch \
	file://0726-fix-stm32-rif-extend-behaviour-of-peripheral-access-.patch \
	file://0727-fix-st-clock-remove-mux-access-when-m33tdcid.patch \
	file://0728-fix-stm32mp2-remove-Tamper-access-when-M33-is-TDCID.patch \
	file://0729-feat-stm32mp2-disable-RNG-init-when-M33-is-TDCID.patch \
	file://0730-feat-stm32mp2-add-synchronization-point-between-CA35.patch \
	file://0731-fix-stm32mp2-remove-rifsc-function-usage.patch \
	file://0732-fix-st-clock-remove-CLK_CFG-CMD_CLK-support-for-st-k.patch \
	file://0733-feat-fdts-update-stm32mp215f-dk-system-configuration.patch \
	file://0734-fix-stm32mp2-use-BIT_32-marco-instead-of-BIT.patch \
	file://0735-feat-stm32mp2-increase-extra-partition-for-M33TDCID.patch \
	file://0736-feat-stm32mp2-force-boot-interface-instance-on-M33TD.patch \
	file://0737-feat-stm32mp2-map-bsec_mirror-area-as-non-secure.patch \
	file://0738-feat-stm32mp2-forbid-upper-OTP-access-with-mirror.patch \
	file://0739-refactor-stm32mp2-align-bl31_plat_get_next_image_ep_.patch \
	file://0740-fix-stm32mp2-reduce-BL2-read-only-part-size-on-trust.patch \
	file://0741-fix-stm32mp21-fdts-new-LPDDR4-LP4WL-setting-for-STM3.patch \
	file://0742-fix-stm32mp25-fdts-new-DDR4-density-comment-for-STM3.patch \
	file://0743-feat-st-add-RNG-minor-version.patch \
	file://0744-fix-st-crypto-improve-RNG-health-test-configuration.patch \
	file://0745-docs-dt-bindings-add-RNG-customization-optional-prop.patch \
	file://0746-refactor-st-crypto-split-RNG-NIST-configuration.patch \
	file://0747-feat-st-crypto-manage-RNG-customization-with-device-.patch \
	file://0748-fix-stm32mp2-fix-CID-filtering-for-PWR_CPU2CR.patch \
	file://0749-fix-stm32mp2-fix-CID-filtering-for-EXTI2_CmIMRx.patch \
	file://0750-fix-stm32mp2-fix-shutdown-on-STM32MP21.patch \
	file://0751-fix-stm32mp2-remove-warning-in-stm32_system_off.patch \
	file://0752-fix-stm32mp2-use-TOOL_ADD_IMG_PAYLOAD-for-BL31-DT.patch \
	file://0753-fix-stm32mp2-authorize-the-LPLV-Stop2-for-GPIO-wakeu.patch \
	file://0754-fix-st-set-no-pie-option-when-building-ST-elf-file.patch \
	file://0755-fix-st-pmic-remove-deadcode-from-STPMIC2-driver.patch \
	file://0756-fix-fdts-set-flexgen-58-to-HSE_KER-for-STM32MP257F-E.patch \
	file://0757-fix-psci-Allow-return-to-aarch32-smc-caller.patch \
	file://0758-clk-clk-stm32-core-add-trace-for-unknown-clock-ident.patch \
	file://0759-feat-stm32mp2-boot-BL33-at-EL2-by-default.patch \
	file://0760-feat-stm32mp2-clear-all-IAC-when-serial-programmer-i.patch \
	file://0761-feat-st-clk-add-ck_bus_risaf4-clock-for-STM32MP2.patch \
	file://0762-feat-st-clock-rename-RCC_USBTCCFGR-register-into-RCC.patch \
	file://0763-Revert-feat-stm32mp2-limit-low-power-mode-when-corte.patch \
	file://0764-feat-stm32mp2-workaround-implementation-for-D1-D2-lo.patch \
	file://0765-refactor-stm32mp2-make-stm32_pwr_cpu2_state_is_runni.patch \
	file://0766-feat-build-add-ability-to-define-platform-specific-d.patch \
	file://0767-fix-stm32mp2-fdts-set-SDMMC-max-frequency-to-166-MHz.patch \
	file://0768-fix-stm32mp2-fdts-set-SDMMC-max-frequency-to-166-MHz.patch \
	file://0769-fix-stm32mp2-fdts-set-SDMMC-max-frequency-to-166-MHz.patch \
	file://0770-fix-st-ddr-bad-refresh-update-level-toggle-sequence.patch \
	file://0771-feat-st-bsec-add-support-of-HDPL-for-STM32MP21.patch \
	file://0772-feat-stm32mp2-increment-HDPL-before-booting-BL31.patch \
	file://0773-fix-st-ddr-change-retention-disable-management.patch \
	file://0774-fix-stm32mp2-save-lpsram_amen-in-low-power-context.patch \
	file://0775-feat-stm32mp2-update-struct-otp_mirror.patch \
	file://0776-fix-stm32mp2-remove-stm32mp2_ddr_helpers-for-M33-TDC.patch \
	file://0777-feat-stm32mp2-update-stm32mp_system_reset-for-M33-TD.patch \
	file://0778-fix-stm32mp-drivers-stm32_iwdg-remove-num_irq.patch \
	file://0779-fix-cert-create-load-openSSL-configuration-before-PK.patch \
	file://0780-fix-build-do-not-force-PLAT-in-plat_helpers.mk.patch \
	file://0781-fix-st-clock-remove-TODO-in-STM32MP2-clock-driver.patch \
	file://0782-feat-st-crypto-improve-RNG-parameter-for-all-platfor.patch \
	file://0783-fix-st-crypto-increase-RNG-robustness-for-STM32MP21.patch \
	file://0784-feat-stm32mp2-configure-TAMP-before-reading-TAMP_SR.patch \
	file://0785-feat-stm32mp2-save-IAC-earlier-in-the-boot.patch \
	file://0786-feat-fdts-update-SPI-NOR-partition-offsets-for-M33TD.patch \
	file://0787-feat-st-spi-remove-memory-mapped-support-on-M33TD.patch \
	file://0788-feat-stm32mp2-support-CPU1-reset-for-M33-TDCID.patch \
	file://0789-fix-stm32mp2-clear-low-power-context-on-standby-exit.patch \
	file://0790-feat-build-add-encrypted-payload-as-FIP-dependency.patch \
	file://0791-fix-stm32mp2-correct-BL31-DT-encryption.patch \
	file://0792-fix-stm32mp2-correct-early-crash-console-init.patch \
	file://0793-feat-stm32mp1-move-DDR-training-area-restore-on-low-.patch \
	file://0794-refactor-st-ddr-remove-DDR-training-area-restore-fro.patch \
	file://0795-refactor-st-bsec-fix-bsec-state-initialisation.patch \
	file://0796-feat-stm32mp2-rename-stm32_otp_is_closed_device-to-s.patch \
	file://0797-feat-stm32mp2-add-sanity-check-in-low-power-context.patch \
	file://0798-feat-stm32mp1-add-crc-in-low-power-mode-context.patch \
	file://0799-fix-stm32mp2-fdts-put-DDR-firmware-under-flag-in-stm.patch \
	file://0800-fix-stm32mp2-support-cortex-M33-as-TDCID-in-STM32MP2.patch \
	file://0801-fix-stm32mp2-restore-system-for-warmboot-after-D1-DS.patch \
	file://0802-feat-st-rework-setup-of-SVC-services.patch \
	file://0803-feat-stm32mp2-add-CPU-compatible-define.patch \
	file://0804-feat-st-export-stm32mp_get_part_number.patch \
	file://0805-feat-st-add-SMC-error-codes-on-going-and-no-perm.patch \
	file://0806-feat-st-clock-export-needed-functions-for-ca35ss_clk.patch \
	file://0807-feat-stm32mp2-add-SMC-services-for-CA35SS-clock-scal.patch \
	file://0808-feat-stm32mp2-register-SMC-services-for-CA35SS-clock.patch \
	file://0809-feat-st-Update-metadata-and-fip-offset-for-nor.patch \
	file://0810-fix-st-ddr-remove-TODO-in-STM32MP2-driver.patch \
	file://0811-feat-st-use-BL33-parameter-x0-for-physical-address-o.patch \
	file://0812-feat-stm32mp2-pwr-syscfg-allow-to-set-a-fixed-IO-com.patch \
	file://0813-feat-stm32mp2-fdts-add-fixed-IO-compensation-on-vddi.patch \
	file://0814-feat-stm32mp2-fdts-add-fixed-IO-compensation-on-vddi.patch \
	file://0815-feat-stm32mp2-fdts-add-fixed-IO-compensation-on-vddi.patch \
	file://0816-fix-st-clock-don-t-change-flexgen-for-CM33-TDCID-on-.patch \
	file://0817-refactor-stm32mp21-remove-CCB-register.patch \
	file://0818-refactor-stm32mp21-remove-CCB-bindings.patch \
	file://0819-feat-st-pmic-add-default-regulator-configuration-for.patch \
	file://0820-feat-stm32mp2-fdts-remove-ramp-delay-on-ddr-supply.patch \
	file://0821-fix-stm32mp2-fix-system-off-on-STM32MP25.patch \
	file://0822-feat-st-drivers-stm32_iwdg-set-watchdog-timeout-from.patch \
	file://0823-feat-stm32mp2-add-SCMI-secure-shmem-in-memory-map-fo.patch \
	file://0824-feat-stm32mp2-add-IPCC-base-addresses.patch \
	file://0825-feat-stm32mp2-add-simple-a-simple-SCMI-voltd-client-.patch \
	file://0826-feat-stm32mp2-add-support-for-CA35SS-voltage-scaling.patch \
	file://0827-feat-st-add-check-to-function-linked-to-NVMEM.patch \
	file://0828-fix-stm32mp2-fdts-remove-eMMC-support-on-stm32mp215f.patch \
	file://0829-fix-st-crypto-parse-RNG-DT-before-interacting-with-t.patch \
	file://0830-refactor-st-sdmmc2-data-timeout-calculation-based-on.patch \
	file://0831-fix-st-usb-issue-stall-on-EP0-inside-usb-stop.patch \
	file://0832-fix-st-replace-down-counter-by-a-timeout-upon-dfu-de.patch \
	file://0833-fix-st-uart-aarch64-unwait-for-UART-ISR-register-TC-.patch \
	file://0834-fix-st-uart-aarch64-wait-for-UART-ISR-register-TC-bi.patch \
	file://0835-fix-stm32mp2-flush-the-console-when-going-in-suspend.patch \
	file://0836-fix-st-uart-aarch32-remove-unecessary-timeout-waitin.patch \
	file://0837-fix-st-uart-aarch32-wait-for-UART-ISR-register-TC-bi.patch \
	file://0838-refactor-stm32mp1-update-SPDX-license.patch \
	file://0839-refactor-stm32mp2-update-SPDX-license.patch \
	file://0840-fix-stm32mp23-define-VOLTD_SCMI_STPMIC2_BUCK.patch \
	file://0841-fix-rss-fix-bound-check-during-protocol-selection.patch \
	file://0842-feat-rss-adjust-parameter-packing-to-match-TF-M-chan.patch \
	file://0843-feat-rss-add-defines-for-type-range-and-use-them-in-.patch \
	file://0844-feat-mhu-use-compile-flag-to-choose-mhu-version.patch \
	file://0845-fix-mhu-use-MHUv2-if-PLAT_MHU_VERSION-undefined.patch \
	file://0846-refactor-tc-update-platform-tests.patch \
	file://0847-fix-psa-fix-static-check-failure.patch \
	file://0848-refactor-rss-rename-all-rss-files-to-rse.patch \
	file://0849-docs-rename-all-rss-files-to-rse.patch \
	file://0850-refactor-psa-rename-all-rss-files-to-rse.patch \
	file://0851-refactor-rse-change-all-occurrences-of-RSS-to-RSE.patch \
	file://0852-docs-change-all-occurrences-of-RSS-to-RSE.patch \
	file://0853-refactor-psa-change-all-occurrences-of-RSS-to-RSE.patch \
	file://0854-refactor-changelog-change-all-occurrences-of-RSS-to-.patch \
	file://0855-fix-rse-include-lib-psa-to-resolve-build.patch \
	file://0856-fix-arm-correct-RSE_CRYPTO_EXPORT_PUBLIC_KEY_SID.patch \
	file://0857-fix-psa-guard-Crypto-APIs-with-CRYPTO_SUPPORT.patch \
	file://0858-feat-psa-add-interface-with-RSE-for-retrieving-entro.patch \
	file://0859-refactor-arm-rename-PLAT_MHU_VERSION-flag.patch \
	file://0860-refactor-rse-put-MHU-code-in-a-dedicated-file.patch \
	file://0861-refactor-rse-remove-rse_comms_init.patch \
	file://0862-feat-st-add-RSE-comms-support-for-ST-platforms.patch \
	file://0863-feat-stm32mp2-enable-rse-support.patch \
	file://0864-fix-st-ddr-skip-DDR-power-init-on-standby-exit-for-S.patch \
	file://0865-fix-stm32mp1-reorder-DDR3-power-supply-sequence.patch \
	file://0866-fix-stm32mp2-reorder-DDR3-and-DDR4-power-supply-sequ.patch \
	file://0867-fix-st-ddr-improve-error-management-during-PHY-init-.patch \
	file://0868-feat-stm32mp2-allow-booting-Linux-directly.patch \
	file://0869-fix-stm32mp2-Manage-D3-autonomous-clocking-workaroun.patch \
	file://0870-fix-st-correct-endxfer-polling.patch \
	file://0871-fix-stm32mp2-support-cortex-M33-as-TDCID-in-STM32MP2.patch \
	file://0872-refactor-stm32mp23-fdts-remove-pinctrl-DT-file.patch \
	file://0873-fix-st-ddr-remove-useless-CONFIG_STM32MP25X_REVA-fla.patch \
	file://0874-fix-stm32mp2-maintain-only-BKPSRAM-content-in-power-.patch \
	file://0875-feat-st-use-and-override-default-MBedTLS-config.patch \
	file://0876-fix-st-bsec-update-bsec-state-to-match-other-compone.patch \
	file://0877-feat-stm32mp2-add-M33TDCID-secure-boot-support.patch \
	file://0878-feat-st-pmic-simplify-usage-of-initialize_pmic.patch \
	file://0879-feat-st-pmic-display-information-only-in-BL2.patch \
	file://0880-feat-stm32mp2-add-DDR-power-OFF-function.patch \
	file://0881-feat-stm32mp2-call-stm32mp_board_ddr_power_off-in-po.patch \
	file://0882-feat-st-bsec-add-support-of-HDPL-increment-in-M33TD.patch \
	file://0883-fix-compiler-rt-force-usage-of-__popcountdi2.patch \
	file://0884-fix-stm32mp2-increase-stack-size-when-Mbed-TLS-is-us.patch \
	file://0885-feat-stm32mp21-add-CRYP-node-in-STM32MP21-platforms.patch \
	file://0886-refactor-st-crypto-add-a-crypto-common-header.patch \
	file://0887-feat-st-crypto-add-AES-decrypt-auth-by-CRYP-peripher.patch \
	file://0888-refactor-stm32mp2-update-rif.h-to-meet-MISRA-expecta.patch \
	file://0889-feat-stm32mp2-configure-RIFSC-to-manage-CRYP1-in-the.patch \
	file://0890-fix-stm32mp2-correct-the-Boolean-logic-in-the-RIFSC-.patch \
	file://0891-feat-psa-add-standard-IOCTL-RSE-call.patch \
	file://0892-feat-stm32mp2-add-stm32mp-rse-comm-specific-function.patch \
	file://0893-feat-stm32mp2-add-M33TDCID-encrypted-boot-support.patch \
	file://0894-fix-st-pmic-display-complete-product-ID.patch \
	file://0895-plat-stm32mp2-add-a-ca35ss-driver.patch \
	file://0896-plat-stm32mp2-add-stm32mp_ca35_configure_opp.patch \
	file://0897-feat-st-clock-add-the-needed-function-for-ca35ss_clk.patch \
	file://0898-feat-stm32mp2-fix-support-for-CA35SS-voltage-scaling.patch \
	file://0899-feat-drivers-scmi-add-define-for-SCMI-protocol-17.patch \
	file://0900-fix-stm32mp2-fix-scmi-driver.patch \
	file://0901-feat-stm32mp2-rework-SCMI-driver.patch \
	file://0902-feat-stm32mp2-add-support-of-token-in-SCMI-messages.patch \
	file://0903-feat-stm32mp2-add-SCMI-system-power-management-proto.patch \
	file://0904-feat-stm32mp2-use-SCMI-power-state-protocol-for-CM33.patch \
	file://0905-fix-stm32mp2-put-crash-console-clocks-under-TDCID-fl.patch \
	file://0906-feat-stm32mp2-set-DDR-in-self-refresh-in-system-off-.patch \
	file://0907-Add-delete_interrupt_type_handler-function.patch \
	file://0908-fix-stm32mp2-handle-power-down-on-secondary-core.patch \
	file://0909-fix-stm32mp2-restore-the-PSCI-system-reset-in-serial.patch \
	file://0910-feat-st-spi-restore-memory-mapped-support-on-M33TD.patch \
	file://0911-fix-stm32mp2-prevent-panic-when-external-oscillator-.patch \
	file://0912-fix-stm32mp13-prevent-panic-when-external-oscillator.patch \
	file://0913-fix-st-uart-aarch32-fix-ISR-bit-use-for-console-flus.patch \
	file://0914-fix-build-enforce-single-partition-for-LTO-build.patch \
	file://0915-feat-stm32mp-add-stack-protector-support.patch \
	file://0916-perf-st-spi-improve-memory-mapped-read-throughput.patch \
	file://0917-perf-st-spi-improve-indirect-read-write-throughput.patch \
	file://0918-perf-stm32mp2-fdts-set-OSPI-clock-at-266-MHz-when-ne.patch \
	file://0919-perf-st-spi-improve-memory-mapped-read-throughput.patch \
	file://0920-perf-st-spi-improve-indirect-read-write-throughput.patch \
	file://0921-fix-stm32mp25-fdts-new-swizzle-configuration-for-STM.patch \
	file://0922-feat-clk-support-multiple-clock-providers-via-clock-.patch \
	file://0923-feat-st-clock-use-clk_add_default_provider-to-regist.patch \
	file://0924-feat-fdt-wrappers-fdt_get_phandle_with_args-function.patch \
	file://0925-feat-st-add-interface-to-get-a-clock-by-an-index-fro.patch \
	file://0926-feat-clk-introduce-support-of-fixed-clock.patch \
	file://0927-feat-stm32mp2-register-all-fixed-clocks-at-startup.patch \
	file://0928-feat-st-spi-add-fixed-clock-support-in-stm32_ospi_in.patch \
	file://0929-fix-stm32mp2-Reduce-ICN-QOS-VDEC-priority-from-4-to-.patch \
	file://0930-feat-stm32mp2-fix-shmem-channel-status-read-access.patch \
	file://0931-fix-stm32mp2-increase-scmi-timeout.patch \
	file://0932-fix-stm32mp2-change-scmi-system-power-request-to-for.patch \
	file://0933-fix-nand-add-read-parameter-page-retry.patch \
	file://0934-feat-st-clk-increase-startup-timeout-for-oscillators.patch \
	file://0935-feat-st-clk-increase-startup-timeout-for-oscillators.patch \
	file://0936-fix-st-ddr-manage-semaphore-with-CID-filtering.patch \
	file://0937-refactor-stm32mp1-print-reset-reason-at-a-lower-log-.patch \
	file://0938-refactor-stm32mp2-print-reset-reason-at-a-lower-log-.patch \
	file://0939-fix-stm32mp2-configure-STOP2-entry-point-when-needed.patch \
	file://0940-fix-stm32mp1-increase-STM32MP_BL2_SIZE.patch \
	file://0941-feat-stm32mp1-set-stm32_pwr_down_wfi_wrapper-multipr.patch \
	file://0942-feat-stm32mp1-filter-mode-in-stm32_pwr_down_wfi_load.patch \
	file://0943-feat-stm32mp1-add-PSCI-OSI-low-power-request.patch \
	file://0944-fix-stm32mp1-use-GIC-in-BL2.patch \
	file://0945-feat-stm32mp1-implement-a-wake-up-of-the-primary-CPU.patch \
	file://0946-feat-fdts-add-DDR4-1x16Gbit-1x16bit-1200MHz-configur.patch \
	file://0947-fix-st-prevent-try_cnt-from-being-decremented-below-.patch \
	file://0948-feat-partition-add-function-to-retrieve-entry-by-par.patch \
	file://0949-feat-efi-add-specific-GUIDs-for-metadata-partitions.patch \
	file://0950-fix-st-rework-metadata-partition-selection.patch \
	file://0951-fix-st-avoid-enormous-tf-a-stm32mp13-stm32.patch \
	file://0952-fix-mmc-increase-MMC_DEFAULT_MAX_RETRIES.patch \
	file://0953-fix-stm32mp2-enable-VDDIO3SV-and-VDDIO4SV.patch \
	file://0954-feat-stm32mp2-add-support-for-STM32MP25xx-DHCOS-SoM-.patch \
	"
